services:
  # Backend API
  backend-api:
    image: talel12/api-session14
    container_name: backend-api
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./backup:/data/db
    networks:
      - mongodb-volume

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    networks:
      - mongodb-volume

volumes:
  database-volume:


networks:
  mongodb-volume: